### ISSUE TITLE
project删掉后重建同名项目进入docker失败

### ISSUE THREAD

**Issue by qianhuihan** [emmYouAreRight/AZFT-IoT-Backend#1]
新建一个已被删掉的project后，再开启Docker时会报错，redis的问题，进行改进优化

**Comment by zhaoskyfucker** [comment]
上次我修补以后，还会出这样的问题？

**Comment by qianhuihan** [comment]
之前在webide的仓库里，然后移到这边了，刚刚试了一下，已经解决了，那我close掉。
